# Generated by Django 4.0.5 on 2022-08-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('descripcion', models.TextField(max_length=255, verbose_name='descripcion')),
                ('fecha_inicio', models.DateField(default=0)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, verbose_name='cargo')),
                ('descripcion', models.TextField(max_length=255, verbose_name='descripcion')),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=255, verbose_name='nombres_apellidos')),
                ('cedula', models.CharField(max_length=255, verbose_name='nombres_apellidos')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('sexo', models.CharField(max_length=15, verbose_name='sexo_noasociado')),
                ('comunidad', models.CharField(max_length=255, verbose_name='comunidad')),
                ('municipio', models.CharField(max_length=255, verbose_name='municipio')),
                ('departamento', models.CharField(max_length=255, verbose_name='departamento')),
                ('padrino', models.CharField(max_length=255, verbose_name='nombres_apellidos')),
                ('contacto', models.IntegerField(verbose_name='contacto')),
                ('rubro', models.CharField(max_length=255, verbose_name='rubro_noasociado')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=255, verbose_name='programa')),
                ('nombre_abreviado', models.CharField(max_length=255, verbose_name='nombre_abreviado')),
                ('descripcion', models.TextField(max_length=255, verbose_name='descripcion')),
                ('fecha_inicio', models.DateField(default=0)),
                ('fecha_finalizacion', models.DateField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=255, verbose_name='Programa')),
                ('descripcion', models.TextField(max_length=255, verbose_name='descripcion')),
                ('presupuesto', models.FloatField(default=0.0)),
                ('fecha_inicio', models.DateField(default=0)),
                ('fecha_finalizacion', models.DateField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('programa', models.ManyToManyField(to='catalogos.programasmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('cedula', models.CharField(max_length=14, verbose_name='cedula')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('fecha_asociacion', models.DateField(verbose_name='fecha_asociacion')),
                ('sexo', models.CharField(max_length=255, verbose_name='sexo')),
                ('comunidad', models.CharField(max_length=255, verbose_name='comunidad')),
                ('municipio', models.CharField(max_length=255, verbose_name='municipio')),
                ('departamento', models.CharField(max_length=255, verbose_name='departamento')),
                ('latitud', models.FloatField(verbose_name='latitud')),
                ('longitud', models.FloatField(verbose_name='longitud')),
                ('rubros', models.CharField(max_length=100, verbose_name='rubros')),
                ('manzanas_suelos', models.IntegerField(verbose_name='manzanas_suelos')),
                ('num_update', models.IntegerField(verbose_name='num_update')),
                ('actualizado', models.BooleanField(verbose_name='actualizado')),
            ],
        ),
        migrations.CreateModel(
            name='TemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255, verbose_name='tema')),
                ('proyecto', models.ManyToManyField(to='catalogos.proyectomodel')),
            ],
        ),
        migrations.CreateModel(
            name='TecnicosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres_apellidos', models.CharField(max_length=255, verbose_name='Nombres_apellidos')),
                ('created', models.DateField(auto_now=True)),
                ('area', models.ManyToManyField(to='catalogos.areamodel')),
                ('cargo', models.ManyToManyField(to='catalogos.cargomodel')),
            ],
        ),
    ]
