# Generated by Django 4.1.2 on 2022-12-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectomodel',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='temamodel',
            name='proyecto',
        ),
        migrations.AlterField(
            model_name='proyectomodel',
            name='proyecto',
            field=models.CharField(max_length=255, verbose_name='Proyecto'),
        ),
    ]
