# Generated by Django 4.0.5 on 2022-08-09 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=255, verbose_name='asesor tecnico')),
                ('id_curren_user', models.IntegerField(default=0)),
                ('comunidad', models.CharField(max_length=255, verbose_name='comunidad')),
                ('municipio', models.CharField(max_length=255, verbose_name='municipio')),
                ('departamento', models.CharField(max_length=255, verbose_name='departamento')),
                ('fecha', models.DateField(max_length=255, verbose_name='fecha')),
                ('tema', models.CharField(max_length=255, verbose_name='tema')),
                ('programa', models.CharField(max_length=255, verbose_name='programa')),
                ('proyecto', models.CharField(max_length=255, verbose_name='Proyecto')),
                ('conc_cap', models.IntegerField()),
            ],
            options={
                'unique_together': {('id_curren_user', 'conc_cap')},
            },
        ),
        migrations.CreateModel(
            name='Participantes_capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('nombres_apellidos', models.CharField(max_length=255, verbose_name='nombres_y_apellidos')),
                ('cedula', models.CharField(max_length=255, verbose_name='cedula')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(default='1', max_length=15, verbose_name='sexo')),
                ('departamento', models.CharField(default='Jinotega', max_length=255, verbose_name='departamento')),
                ('municipio', models.CharField(default='Jinotega', max_length=100, verbose_name='departamento')),
                ('comunidad', models.CharField(default='Jinotega', max_length=100, verbose_name='comunidad')),
                ('rubro', models.CharField(blank=True, default='otro', max_length=255, null=True, verbose_name='rubro')),
                ('manzanas_suelo', models.FloatField(default=0)),
                ('latitud', models.FloatField(default=0.0, verbose_name='latitud')),
                ('longitud', models.FloatField(default=0.0, verbose_name='longitud')),
                ('estado', models.CharField(default='', max_length=255, verbose_name='estado')),
                ('fecha_asociacion', models.CharField(default='', max_length=255, verbose_name='fecha_asociacion')),
                ('id_rel_capacitacion', models.IntegerField(default=0)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_capacitacion', to='capacitaciones.capacitaciones')),
            ],
            options={
                'ordering': ['cod'],
            },
        ),
    ]
