# Generated by Django 4.0.5 on 2022-07-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='id_curren_user',
            field=models.IntegerField(default=0),
        ),
    ]
