# Generated by Django 4.0.5 on 2022-07-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_alter_capacitaciones_id_curren_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capacitaciones',
            unique_together={('id_curren_user', 'conc_cap')},
        ),
    ]
