# Generated by Django 4.0.5 on 2022-07-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0003_alter_capacitaciones_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capacitaciones',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='capacitaciones',
            name='conc_cap',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='capacitaciones',
            unique_together={('conc_cap',)},
        ),
    ]
