# Generated by Django 4.0.5 on 2022-07-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0005_alter_capacitaciones_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capacitaciones',
            unique_together=set(),
        ),
    ]
