# Generated by Django 4.0.5 on 2022-08-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0007_alter_capacitaciones_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitaciones',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
