# Generated by Django 4.0.5 on 2022-08-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beneficioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.CharField(max_length=255, verbose_name='beneficio')),
                ('creado', models.DateField(auto_now=True)),
            ],
        ),
    ]
