# Generated by Django 4.0.5 on 2022-08-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunidadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=255, verbose_name='municipio')),
                ('comunidad', models.ManyToManyField(to='departamentos.comunidadmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=255, verbose_name='departamento')),
                ('municipio', models.ManyToManyField(to='departamentos.municipiomodel')),
            ],
        ),
    ]
